### ISSUE TITLE
Update Documentation and clean go.yml 

### ISSUE THREAD

**Issue by kanirudh** [parmaanu/goutils#3]
- [ ] Add documentation about different util packages in the README.md

- [ ] Does following configuration mean builds will only run on commit and pull request merge to `main` branch?  
Do we want that or we want to run builds and tests on every commit?
```
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
```
- [ ] Is there any option to disable merging unless all comments are resolved?
- [x] Is there any option to disable merging unless all builds are success?
- [x] Does it fetch and install golang everytime?
- [x] Does it fetch and install dependencies everytime?
- [x] We are using `go modules` and never gonna use `go dep`. It's better to remove following config
```
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
```
- [x] What does following config do? If it is not relevant then we should remove it.
```
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
```
- [x] What is this setup-go@v2? If it is not used, then we should remove it.
```
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
```

**Comment by Viv1k** [comment]
@kanirudh, please take care of above points. 
Thanks

**Comment by kanirudh** [comment]
From my understanding the following happens, and every step does something in the go.yml. Its a standard template created by github CI 

Example run
https://github.com/parmaanu/goutils/runs/1472039334?check_suite_focus=true

A Docker container is requisitioned
It installs golang, so yes, I think it does there is some caching because it finishes in 2s
Then it checkout out the code
Will remove the go dep checkout procedure


I made a change in the github setting, to require atleast 1 approval on each pull request before we can merge it to main.

won't the reviewer not give an approval if any open comment is there ?

From what I am seeing
1. if a pull request is created for the main branch it will run the tests
2. If we update the pull request it will run the tests

That seems good enough, any case we are missing ?
